### ISSUE TITLE
beakerlib 1.17 does not handle well kernel/base library

### ISSUE THREAD

**Issue by bgoncalv** [beakerlib/beakerlib#20] opened 2017-11-21 14:07 UTC
kernel/base library is available as part of beakerlib-libraries, and it seems since beakerlib 1.17 it does not handle the library correctly.

Tested with https://upstreamfirst.fedorainfracloud.org/nfs-utils/blob/master/f/exportfs/runtest.sh

    # rpm -q beakerlib
    beakerlib-1.17-4.fc28.noarch

    # dnf copr enable mvadkert/beakerlib-libraries -y
    Repository successfully enabled.

    # dnf install beakerlib-libraries
    <snip>

    # ./runtest.sh 

    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    ::   do-Setup
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

    :: [ 13:55:26 ] :: [   INFO   ] :: rlImport: Found 'kernel/base' in /usr/share/beakerlib-libraries
    :: [ 13:55:26 ] :: [   INFO   ] :: rlImport: Will try to import kernel/base from /usr/share/beakerlib-libraries/kernel/Library/base/lib.sh
    /usr/share/beakerlib/logging.sh: line 104: /mnt/tests/unknown/output.log: No such file or directory
    :: [ 13:55:27 ] :: [   INFO   ] :: output log will be stored in /mnt/tests/unknown/output.log
    {INFO} Test env info:
    ------------------------------------------------
    Time & CURDIR : [2017-11-21 13:55:27 @/root/nfs-utils/exportfs]
    Case Name     : unknown
    $HOSTNAME     : localhost.localdomain
    /usr/share/beakerlib-libraries/kernel/Library/base/lib.sh: line 299: lsb_release: command not found
    Distro Info   :  : 
    NVR & host    : Linux localhost.localdomain 4.15.0-0.rc0.git1.1.fc28.x86_64 #1 SMP Mon Nov 13 19:54:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    cmdline       :
        BOOT_IMAGE=/boot/vmlinuz-4.15.0-0.rc0.git1.1.fc28.x86_64 root=UUID=46f142a6-b4a4-4795-adc3-726609b3e796 ro no_timer_check console=tty1 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 LANG=en_US.UTF-8
    Package Info  :
        rpm: no arguments given for query
    ------------------------------------------------

    :: [ 13:55:27 ] :: [   INFO   ] :: using '/var/tmp/beakerlib-flcBsc8/backup' as backup destination
    :: [ 13:55:27 ] :: [   INFO   ] :: using '/var/tmp/beakerlib-flcBsc8/backup' as backup destination

    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    ::   unknown
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

    [13:55:27 root@ ~~]# rm -f /etc/exports.d/*
    :: [ 13:55:27 ] :: [   PASS   ] :: Running 'rm -f /etc/exports.d/*' (Expected 0, got 0)
    --------------------------------------------------------------------------------

    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    ::   unknown
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

    [13:55:27 root@ ~~]# mkdir -p $nfsmp $expdir
    :: [ 13:55:27 ] :: [   PASS   ] :: Running 'mkdir -p $nfsmp $expdir' (Expected 0, got 0)
    --------------------------------------------------------------------------------

    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    ::   unknown
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

    [13:55:27 root@ ~~]# echo "$expdir *(rw,no_root_squash,fsid=0)" > /etc/exports
    :: [ 13:55:27 ] :: [   PASS   ] :: Running 'echo "$expdir *(rw,no_root_squash,fsid=0)" > /etc/exports' (Expected 0, got 0)
    --------------------------------------------------------------------------------
    Redirecting to /bin/systemctl start nfs.service
    ________________________________________________________________________________
    :: [ 13:55:28 ] :: [   LOG    ] :: Duration: 1s
    :: [ 13:55:28 ] :: [   LOG    ] :: Assertions: 1 good, 0 bad
    :: [ 13:55:28 ] :: [   PASS   ] :: RESULT: unknown

    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    ::   do-Test-exportfs-with-wrong-option
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

    <snip>

**Comment by bgoncalv** [comment] 2017-11-21 14:09
With version 1.16 it works well.

    # dnf downgrade -y https://kojipkgs.fedoraproject.org//packages/beakerlib/1.16/4.fc27/noarch/beakerlib-1.16-4.fc27.noarch.rpm

    # export BEAKERLIB_LIBRARY_PATH=/usr/share/beakerlib-libraries

    # ./runtest.sh 

    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    :: [   LOG    ] :: do-Setup
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

    :: [ 13:59:25 ] :: [ INFO    ] :: rlImport: Found 'kernel/base' in BEAKERLIB_LIBRARY_PATH
    :: [ 13:59:25 ] :: [ INFO    ] :: rlImport: Will try to import kernel/base from /usr/share/beakerlib-libraries/kernel/Library/base/lib.sh
    :: [ 13:59:25 ] :: [ INFO    ] :: output log will be stored in /mnt/tests//output.log
    {INFO} Test env info:
    ------------------------------------------------
    Time & CURDIR : [2017-11-21 13:59:25 @/root/nfs-utils/exportfs]
    Case Name     : 
    $HOSTNAME     : localhost.localdomain
    /usr/share/beakerlib-libraries/kernel/Library/base/lib.sh: line 299: lsb_release: command not found
    Distro Info   :  : 
    NVR & host    : Linux localhost.localdomain 4.15.0-0.rc0.git1.1.fc28.x86_64 #1 SMP Mon Nov 13 19:54:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    cmdline       :
        BOOT_IMAGE=/boot/vmlinuz-4.15.0-0.rc0.git1.1.fc28.x86_64 root=UUID=46f142a6-b4a4-4795-adc3-726609b3e796 ro no_timer_check console=tty1 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 LANG=en_US.UTF-8
    Package Info  :
        rpm: no arguments given for query
    ------------------------------------------------

    :: [ 13:59:25 ] :: [ INFO    ] :: using '/var/tmp/beakerlib-PjnPqYY/backup' as backup destination
    :: [ 13:59:26 ] :: [ INFO    ] :: using '/var/tmp/beakerlib-PjnPqYY/backup' as backup destination
    [13:59:26 root@ ~~]# rm -f /etc/exports.d/*
    :: [   PASS   ] :: Running 'rm -f /etc/exports.d/*' (Expected 0, got 0)
    --------------------------------------------------------------------------------
    [13:59:26 root@ ~~]# mkdir -p $nfsmp $expdir
    :: [   PASS   ] :: Running 'mkdir -p $nfsmp $expdir' (Expected 0, got 0)
    --------------------------------------------------------------------------------
    [13:59:26 root@ ~~]# echo "$expdir *(rw,no_root_squash,fsid=0)" > /etc/exports
    :: [   PASS   ] :: Running 'echo "$expdir *(rw,no_root_squash,fsid=0)" > /etc/exports' (Expected 0, got 0)
    --------------------------------------------------------------------------------
    Redirecting to /bin/systemctl start nfs.service

    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    :: [   LOG    ] :: do-Test-exportfs-with-wrong-option
    <snip>

**Comment by bgoncalv** [comment] 2017-11-21 14:12
I've cloned the test repo to /root/nfs-utils
`git clone https://upstreamfirst.fedorainfracloud.org/nfs-utils.git`
and ran the test on: /root/nfs-utils/exportfs

**Comment by sopos** [comment] 2017-12-12 13:41
this should be fixed by https://github.com/beakerlib/beakerlib/commit/30c5a9b8982e6342cfff28871083f36efc80f52b

**Closed by sopos** 2017-12-12 13:41 UTC

**Comment by bgoncalv** [comment] 2017-12-14 11:54
@sopos thanks for the fix, I just want to confirm is " ::   Test" messages are expected.
tested with `beakerlib-1.17-5.el7.noarch`

    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    ::   do-Setup
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

    :: [ 11:48:45 ] :: [   INFO   ] :: rlImport: Found 'kernel/base' in /usr/share/beakerlib-libraries
    :: [ 11:48:45 ] :: [   INFO   ] :: rlImport: Will try to import kernel/base from /usr/share/beakerlib-libraries/kernel/Library/base/lib.sh
    {INFO} Test env info:
    ------------------------------------------------
    Time & CURDIR : [2017-12-14 11:48:45 @/root/nfs-utils/exportfs]
    Case Name     : 
    $HOSTNAME     : localhost.localdomain
    Distro Info   : Fedora 28 : 
    NVR & host    : Linux localhost.localdomain 4.15.0-0.rc2.git2.1.fc28.x86_64 #1 SMP Thu Dec 7 19:08:25 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    cmdline       :
        BOOT_IMAGE=/boot/vmlinuz-4.15.0-0.rc2.git2.1.fc28.x86_64 root=UUID=ded818ca-1c37-4fd1-9428-2ae1c27774b2 ro no_timer_check console=tty1 console=ttyS0,115200n8 net.ifnames=0 biosdevname=0 LANG=en_US.UTF-8
    Package Info  :
        rpm: no arguments given for query
    ------------------------------------------------

    :: [ 11:48:45 ] :: [   INFO   ] :: using '/var/tmp/beakerlib-73AwY90/backup' as backup destination
    :: [ 11:48:46 ] :: [   INFO   ] :: using '/var/tmp/beakerlib-73AwY90/backup' as backup destination

    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    ::   Test
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

    [11:48:46 root@ ~~]# rm -f /etc/exports.d/*
    :: [ 11:48:46 ] :: [   PASS   ] :: Running 'rm -f /etc/exports.d/*' (Expected 0, got 0)
    --------------------------------------------------------------------------------

    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    ::   Test
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

    [11:48:46 root@ ~~]# mkdir -p $nfsmp $expdir
    :: [ 11:48:46 ] :: [   PASS   ] :: Running 'mkdir -p $nfsmp $expdir' (Expected 0, got 0)
    --------------------------------------------------------------------------------

    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    ::   Test
    ::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

**Comment by sopos** [comment] 2017-12-14 13:44
It would be expected if the rlPhaseStartTest had no argument which is probably not the case. I need to look at it.

**Comment by sopos** [comment] 2017-12-14 14:04
I don't see this issue. I got following output:
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::   do-Setup
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

:: [ 15:02:40 ] :: [   INFO   ] :: rlImport: Found 'kernel/base' in /mnt/tests
:: [ 15:02:40 ] :: [   INFO   ] :: rlImport: Will try to import kernel/base from /mnt/tests/kernel/Library/base/lib.sh
{INFO} Test env info:
------------------------------------------------
Time & CURDIR : [2017-12-14 15:02:41 @/root/test/git/nfs-utils/exportfs]
Case Name     : /nfs-utils/commands/utils/exportfs
$HOSTNAME     : sopos-rhel7-brq.usersys.redhat.com
/mnt/tests/kernel/Library/base/lib.sh: line 294: lsb_release: command not found
Distro Info   :  : 
NVR & host    : Linux sopos-rhel7-brq.usersys.redhat.com 3.10.0-693.el7.x86_64 #1 SMP Thu Jul 6 19:56:57 EDT 2017 x86_64 x86_64 x86_64 GNU/Linux
cmdline       :
        BOOT_IMAGE=/vmlinuz-3.10.0-693.el7.x86_64 root=/dev/mapper/vg_root-lv_root ro crashkernel=auto rd.lvm.lv=vg_root/lv_root rhgb quiet LANG=en_US.UTF-8
Package Info  :
        libnfsidmap-0.25-19.el7.x86_64
        libsss_idmap-1.16.0-12.el7.x86_64
        libtirpc-0.2.4-0.10.el7.x86_64
        nfs-utils-1.3.0-0.52.el7.x86_64
        package nfs-utils-lib is not installed
        rpcbind-0.2.0-43.el7.x86_64
------------------------------------------------

:: [ 15:02:41 ] :: [   INFO   ] :: using '/var/tmp/beakerlib-QxCcvmn/backup' as backup destination
:: [ 15:02:42 ] :: [   INFO   ] :: using '/var/tmp/beakerlib-QxCcvmn/backup' as backup destination

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::   /nfs-utils/commands/utils/exportfs
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

[15:02:42 root@ ~~]# rm -f /etc/exports.d/*
:: [ 15:02:42 ] :: [   PASS   ] :: Running 'rm -f /etc/exports.d/*' (Expected 0, got 0)
--------------------------------------------------------------------------------

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::   /nfs-utils/commands/utils/exportfs
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

[15:02:43 root@ ~~]# mkdir -p $nfsmp $expdir
:: [ 15:02:43 ] :: [   PASS   ] :: Running 'mkdir -p $nfsmp $expdir' (Expected 0, got 0)
--------------------------------------------------------------------------------

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::   /nfs-utils/commands/utils/exportfs
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

**Comment by bgoncalv** [comment] 2017-12-18 15:39
thanks for checking it. The problem might be on `https://pagure.io/beakerlib-libraries/blob/master/f/kernel`. I'll try to debug it further.

**Comment by bgoncalv** [comment] 2017-12-19 08:22
Thanks, so the problem seems to be that on my test the variable `TEST` was not being set. But, is it correct for the test name to be printed during the test execution?

**Comment by sopos** [comment] 2017-12-19 10:25
Yes the original problem was not set TEST variable which caused tee to be trying to write to a file in non-existent path.
The header text seems to be different issue. I'm not sure where the text comes from. Normally, if the rlPhaseStart* does not get any argument, it uses Setup, Test, and Clean respectively. If argument is passed it is used as a phase title.
In your code, I can see phases named do-<something> which I do not see in the output, however your output looks also different so it leads me to conclusion there's something wrong between heaven and hell. I'm not sure what's the root cause of that.
Also I would say you use beakerlib a bit in non-standard way. It would be good to have your testing environment available for investigation of the problem.

**Comment by bgoncalv** [comment] 2017-12-19 14:27
I'm using vagrant [1] to run the test on Fedora Rawhide.

You might need to update `config.vm.box_url` on Vagranfile to use the latest Rawhide build available on [2].

To run the test you can download the Vagrant file and run `vagrant --test-name=nfs-utils up`
After the test finishes you can login to the VM using `vagrant ssh` and check `/tmp/artifacts` for the test logs.

[1] https://github.com/bgoncalv/upstream-testing-vagrant
[2] https://download.fedoraproject.org/pub/fedora/linux/development/rawhide/CloudImages/x86_64/images/

**Comment by sopos** [comment] 2018-01-05 14:20
In new version on beakerlib, we decided to change the meaning of BEAKERLIB_JOURNAL variable. Now it is not set by beakerlib but it can be set by user to specify whether and in which format the journal.xml should be created.
I agree that it was not usual decision as it was not internal variable (prefixed by __INTERNAL) but it was not documented and so we did not guaranteed the content or meaning.
Currently there is internal variable holding that state named __INTERNAL_JOURNAL_OPEN, where value '1' indicates open journal. As this is internal variable, it is subject to change at any time.
If there is a demand for such indicator, please raise an RFE.
